"""add agent_config and working_memory_snapshot

Revision ID: 4d189edbc3f3
Revises: 762bd2494d50
Create Date: 2026-09-19 11:13:38.818477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d189edbc3f3'
down_revision: Union[str, None] = '762bd2494d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('persona_tone', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('script_skeleton', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_entity_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_contact_method', sa.Text(), nullable=True),
    sa.Column('prompt_template_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('working_memory_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('captured_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('script_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objections_raised', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_agent_utterance', sa.Text(), nullable=True),
    sa.Column('disconnect_count', sa.Integer(), nullable=False),
    sa.Column('requires_suppression', sa.Boolean(), nullable=False),
    # create_type=False: the `recording_consent` Postgres ENUM type
    # already exists (created by call_attempt's own column in an
    # earlier migration) -- SQLAlchemy's autogenerate doesn't dedupe
    # enum-type creation across tables/migrations, so without this the
    # migration fails with "type recording_consent already exists".
    sa.Column('recording_consent', postgresql.ENUM('granted', 'denied', 'unclear', 'not_applicable', name='recording_consent', create_type=False), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['call_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_memory_snapshot_attempt_id'), 'working_memory_snapshot', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_memory_snapshot_attempt_id'), table_name='working_memory_snapshot')
    op.drop_table('working_memory_snapshot')
    op.drop_table('agent_config')
    # ### end Alembic commands ###
    # Note: no `sa.Enum(...).drop()` call needed here (unlike Checkpoint
    # 01A's fix) -- this migration never created the recording_consent
    # type (create_type=False above), so it must not drop it either;
    # call_attempt's own column still depends on it.
