"""add provider fields to call_attempt

Revision ID: 762bd2494d50
Revises: de9cafec96b2
Create Date: 2026-09-18 01:26:04.236401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762bd2494d50'
down_revision: Union[str, None] = 'de9cafec96b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_attempt', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('call_attempt', sa.Column('provider_call_id', sa.String(), nullable=True))
    op.create_index('uq_call_attempt_provider_call_id', 'call_attempt', ['provider_call_id'], unique=True, postgresql_where='provider_call_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_call_attempt_provider_call_id', table_name='call_attempt', postgresql_where='provider_call_id IS NOT NULL')
    op.drop_column('call_attempt', 'provider_call_id')
    op.drop_column('call_attempt', 'provider')
    # ### end Alembic commands ###
