"""initial schema

Revision ID: ba7d5a2328d1
Revises: 
Create Date: 2026-09-17 05:54:31.354043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba7d5a2328d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaign_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('normalized_phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Dialing', 'InConversation', 'Disconnected', 'RetryScheduled', 'Reconnecting', 'Completed', 'CompletedPartial', 'Closed', name='contact_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'normalized_phone_number', name='uq_contact_campaign_phone')
    )
    op.create_index('ix_contact_campaign_status', 'contact', ['campaign_id', 'status'], unique=False)
    op.create_table('retry_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_spacing_seconds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('never_connected_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mid_call_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.CheckConstraint('jsonb_array_length(retry_spacing_seconds) = max_retries', name='ck_retry_policy_spacing_matches_max_retries'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('call_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('Initiated', 'Connected', 'FailedToConnect', 'DroppedMidCall', 'EndedNormally', name='call_attempt_state'), nullable=False),
    sa.Column('connection_failure_reason', sa.Enum('no_answer', 'busy', 'invalid_number', 'rejected', 'network_error', 'provider_error', name='never_connected_failure_reason'), nullable=True),
    sa.Column('disconnect_reason', sa.Enum('technical_issue', 'network_problem', 'provider_error', 'ai_error', 'unknown', 'customer_hangup', name='mid_call_disconnect_reason'), nullable=True),
    sa.Column('recording_consent', sa.Enum('granted', 'denied', 'unclear', 'not_applicable', name='recording_consent'), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'attempt_number', name='uq_call_attempt_contact_number')
    )
    op.create_table('suppression',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('agent_in_call', 'manual_api', name='suppression_source'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_suppression_phone_number'), 'suppression', ['phone_number'], unique=False)
    op.create_table('call_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', name='conversation_session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_attempt_id')
    )
    op.create_table('conversation_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('agent', 'contact', 'system', name='conversation_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_conversation_message_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_message')
    op.drop_table('conversation_session')
    op.drop_table('call_event')
    op.drop_index(op.f('ix_suppression_phone_number'), table_name='suppression')
    op.drop_table('suppression')
    op.drop_table('call_attempt')
    op.drop_table('retry_policy')
    op.drop_index('ix_contact_campaign_status', table_name='contact')
    op.drop_table('contact')
    op.drop_table('processed_event')
    op.drop_table('campaign')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Manually added: op.drop_table() does not drop the Postgres ENUM
    # types it implicitly created for sa.Enum() columns -- without this,
    # re-running `upgrade` after a `downgrade` fails with
    # "type ... already exists". Drop in reverse creation order.
    bind = op.get_bind()
    for enum_name in (
        "conversation_role",
        "conversation_session_status",
        "recording_consent",
        "mid_call_disconnect_reason",
        "never_connected_failure_reason",
        "call_attempt_state",
        "suppression_source",
        "contact_status",
        "campaign_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
