"""add call_analysis table for checkpoint 06 post-call intelligence

Revision ID: d15c334bf7e7
Revises: 4d189edbc3f3
Create Date: 2026-09-23 20:41:54.478247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd15c334bf7e7'
down_revision: Union[str, None] = '4d189edbc3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_session_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='analysis_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('intent', sa.Enum('interested', 'not_interested', 'information_requested', 'callback_requested', 'unclear', name='analysis_intent'), nullable=True),
    sa.Column('interest_status', sa.Enum('interested', 'maybe', 'not_interested', 'unknown', name='interest_status'), nullable=True),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', 'mixed', 'unknown', name='analysis_sentiment'), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Enum('follow_up', 'callback', 'send_information', 'sales_contact', 'no_action', 'manual_review', name='analysis_next_action'), nullable=True),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=True),
    sa.Column('input_message_count', sa.Integer(), nullable=True),
    sa.Column('input_duration_seconds', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempt.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['conversation_session_id'], ['conversation_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_attempt_id', name='uq_call_analysis_call_attempt')
    )
    op.create_index('ix_call_analysis_campaign_id', 'call_analysis', ['campaign_id'], unique=False)
    op.create_index('ix_call_analysis_contact_id', 'call_analysis', ['contact_id'], unique=False)
    op.create_index('ix_call_analysis_created_at', 'call_analysis', ['created_at'], unique=False)
    op.create_index('ix_call_analysis_status', 'call_analysis', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_analysis_status', table_name='call_analysis')
    op.drop_index('ix_call_analysis_created_at', table_name='call_analysis')
    op.drop_index('ix_call_analysis_contact_id', table_name='call_analysis')
    op.drop_index('ix_call_analysis_campaign_id', table_name='call_analysis')
    op.drop_table('call_analysis')
    # ### end Alembic commands ###

    # Manually added: op.drop_table() does not drop the Postgres ENUM
    # types it implicitly created for sa.Enum() columns -- same fix as
    # Checkpoint 01A / the initial-schema migration. Drop in reverse
    # creation order.
    bind = op.get_bind()
    for enum_name in (
        "analysis_next_action",
        "analysis_sentiment",
        "interest_status",
        "analysis_intent",
        "analysis_status",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
